### ISSUE TITLE
The code problem

### ISSUE THREAD

**Issue by junzhang-zj** [fwilhelmi/blockchain_enabled_federated_learning#1]
I don't see the code for blockchain components, , could you please solve it?

**Comment by fwilhelmi** [comment]
Dear @junzhang-zj , 

In this repository, we provide a model and simulations related to the delays in a blockchain, so we do not simulate the actual behaviour of a blockchain system by adding components, blocks, etc. In particular, simulations include the results for a queuing system that models the waiting time of transactions in a pool.

Nevertheless, we are now working on an integration of BlockSim (https://github.com/maher243/BlockSim) with TFF, which will be available very soon.

Best,
Francesc.

**Comment by junzhang-zj** [comment]
Thank you for your answer.
